const mockBooksData = [
    {
        "id": 11,
        "title": "The Fault in Our Stars",
        "authors": "John Green",
        "description": "Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazel's story is about to be completely rewritten.Insightful, bold, irreverent, and raw, The Fault in Our Stars is award-winning author John Green's most ambitious and heartbreaking work yet, brilliantly exploring the funny, thrilling, and tragic business of being alive and in love.",
        "edition": "",
        "format": "Hardcover",
        "num_pages": 313,
        "rating": 4.24,
        "rating_count": 2881648,
        "review_count": 147270,
        "genres": "Young Adult, Fiction, Romance, Contemporary",
        "genre_list": "Young Adult,Fiction,Romance,Contemporary",
        "image_url": "https://images.gr-assets.com/books/1360206420l/11870085.jpg",
        "Quote1": "“You don’t forget the face of the person who was your last hope.”",
        "Quote2": "“Remember, we're madly in love, so it's all right to kiss me anytime you feel like it.”",
        "Quote3": "“May the odds be ever in your favor!”"
      },
      {
        "id": 12,
        "title": "The Hitchhiker's Guide to the Galaxy",
        "authors": "Douglas Adams",
        "description": "Seconds before the Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker's Guide to the Galaxy who, for the last fifteen years, has been posing as an out-of-work actor.Together this dynamic pair begin a journey through space aided by quotes from The Hitchhiker's Guide (\"A towel is about the most massively useful thing an interstellar hitchhiker can have\") and a galaxy-full of fellow travelers: Zaphod Beeblebrox—the two-headed, three-armed ex-hippie and totally out-to-lunch president of the galaxy; Trillian, Zaphod's girlfriend (formally Tricia McMillan), whom Arthur tried to pick up at a cocktail party once upon a time zone; Marvin, a paranoid, brilliant, and chronically depressed robot; Veet Voojagig, a former graduate student who is obsessed with the disappearance of all the ballpoint pens he bought over the years.",
        "edition": "",
        "format": "Paperback",
        "num_pages": 193,
        "rating": 4.21,
        "rating_count": 1155911,
        "review_count": 23919,
        "genres": "Science Fiction, Fiction, Humor, Fantasy, Classics",
        "genre_list": "Science Fiction,Fiction,Humor,Fantasy,Classics",
        "image_url": "https://images.gr-assets.com/books/1388282444l/386162.jpg",
        "Quote1": "“Wit beyond measure is man’s greatest treasure.”",
        "Quote2": "“Indifference and neglect often do much more damage than outright dislike.”",
        "Quote3": "“Things we lose have a way of coming back to us in the end, if not always in the way we expect.”"
      },
      {
        "id": 13,
        "title": "The Giving Tree",
        "authors": "Shel Silverstein",
        "description": "\"Once there was a tree...and she loved a little boy.\"So begins a story of unforgettable perception, beautifully written and illustrated by the gifted and versatile Shel Silverstein.Every day the boy would come to the tree to eat her apples, swing from her branches, or slide down her trunk...and the tree was happy. But as the boy grew older he began to want more from the tree, and the tree gave and gave and gave.This is a tender story, touched with sadness, aglow with consolation. Shel Silverstein has created a moving parable for readers of all ages that offers an affecting interpretation of the gift of giving and a serene acceptance of another's capacity to love in return.",
        "edition": "",
        "format": "Hardcover",
        "num_pages": 64,
        "rating": 4.37,
        "rating_count": 789681,
        "review_count": 15694,
        "genres": "Childrens, Childrens, Picture Books, Classics, Fiction",
        "genre_list": "Childrens,Picture Books,Classics,Fiction",
        "image_url": "https://images.gr-assets.com/books/1174210942l/370493.jpg",
        "Quote1": "“Until I feared I would lose it, I never loved to read. One does not love breathing.”",
        "Quote2": "“People generally see what they look for, and hear what they listen for.”",
        "Quote3": "“The one thing that doesn't abide by majority rule is a person's conscience.”"
      },
      {
        "id": 14,
        "title": "Wuthering Heights",
        "authors": "Emily Brontë",
        "description": "You can find the redesigned cover of this edition HERE.This best-selling Norton Critical Edition is based on the 1847 first edition of the novel. For the Fourth Edition, the editor has collated the 1847 text with several modern editions and has corrected a number of variants, including accidentals. The text is accompanied by entirely new explanitory annotations.New to the fourth Edition are twelve of Emily Bronte's letters regarding the publication of the 1847 edition of Wuthering Heights as well as the evolution of the 1850 edition, prose and poetry selections by the author, four reviews of the novel, and poetry selections by the author, four reviews of the novel, and Edward Chitham's insightful and unformative chronology of the creative process behind the beloved work.Five major critical interpretations of Wuthering Heights are included, three of them new to the Fourth Edition. A Stuart Daley considers teh mimportance of chronology in the novel. J. Hillis Miller examines Wuthering Heights's problems of genre and critical reputation. Sandra M. Gilbert asseses the role of Victorian Christianity plays in the novel, while Martha Nussbaum traces the novel's romanticism. Finally, Lin Haire-Sargeant scrutinizes the role of Heathcliff in film adaptations of Wuthering Heights. A Chronology and updated Selected Bibliography are also included.(back cover)",
        "edition": "Fourth Edition",
        "format": "Paperback",
        "num_pages": 464,
        "rating": 3.84,
        "rating_count": 1121100,
        "review_count": 29400,
        "genres": "Classics, Fiction, Romance, Literature",
        "genre_list": "Classics,Fiction,Romance,Literature",
        "image_url": "https://images.gr-assets.com/books/1388212715l/6185.jpg",
        "Quote1": "“A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.”",
        "Quote2": "“It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.”",
        "Quote3": "“I must learn to be content with being happier than I deserve.”"
      },
      {
        "id": 15,
        "title": "The Da Vinci Code",
        "authors": "Dan Brown",
        "description": "An ingenious code hidden in the works of Leonardo da Vinci.A desperate race through the cathedrals and castles of Europe.An astonishing truth concealed for centuries . . . unveiled at last.While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter.Even more startling, the late curator was involved in the Priory of Sion—a secret society whose members included Sir Isaac Newton, Victor Hugo, and Da Vinci—and he guarded a breathtaking historical secret. Unless Langdon and Neveu can decipher the labyrinthine puzzle—while avoiding the faceless adversary who shadows their every move—the explosive, ancient truth will be lost forever.",
        "edition": "",
        "format": "Paperback",
        "num_pages": 481,
        "rating": 3.81,
        "rating_count": 1668594,
        "review_count": 43699,
        "genres": "Fiction, Mystery, Thriller",
        "genre_list": "Fiction,Mystery,Thriller",
        "image_url": "https://images.gr-assets.com/books/1303252999l/968.jpg",
        "Quote1": "“I like the night. Without the dark, we'd never see the stars.”",
        "Quote2": "“I decided as long as I'm going to hell, I might as well do it thoroughly.”",
        "Quote3": "“When life offers you a dream so far beyond any of your expectations, it’s not reasonable to grieve when it comes to an end.”"
      },
]

export default mockBooksData;
