const mockBooksData = [
    {
        "id": 5,
        "title": "Twilight",
        "authors": "Stephenie Meyer",
        "description": "About three things I was absolutely positive.First, Edward was a vampire.Second, there was a part of him—and I didn't know how dominant that part might be—that thirsted for my blood.And third, I was unconditionally and irrevocably in love with him.In the first book of the Twilight Saga, internationally bestselling author Stephenie Meyer introduces Bella Swan and Edward Cullen, a pair of star-crossed lovers whose forbidden relationship ripens against the backdrop of small-town suspicion and a mysterious coven of vampires. This is a love story with bite.",
        "edition": "",
        "format": "Paperback",
        "num_pages": 498,
        "rating": 3.58,
        "rating_count": 4281268,
        "review_count": 97991,
        "genres": "Young Adult, Fantasy, Romance, Paranormal, Vampires, Fiction, Fantasy, Paranormal",
        "genre_list": "Young Adult,Fantasy,Romance,Paranormal,Vampires,Fiction",
        "image_url": "https://images.gr-assets.com/books/1361039443l/41865.jpg",
        "Quote1": "“I like the night. Without the dark, we'd never see the stars.”",
        "Quote2": "“I decided as long as I'm going to hell, I might as well do it thoroughly.”",
        "Quote3": "“When life offers you a dream so far beyond any of your expectations, it’s not reasonable to grieve when it comes to an end.”"
      },
      {
        "id": 6,
        "title": "The Book Thief",
        "authors": "Markus Zusak",
        "description": "Trying to make sense of the horrors of World War II, Death relates the story of Liesel--a young German girl whose book-stealing and story-telling talents help sustain her family and the Jewish man they are hiding, as well as their neighbors.",
        "edition": "First American Edition (US / CAN)",
        "format": "Hardcover",
        "num_pages": 552,
        "rating": 4.36,
        "rating_count": 1485632,
        "review_count": 100821,
        "genres": "Historical, Historical Fiction, Fiction, Young Adult",
        "genre_list": "Historical,Historical Fiction,Fiction,Young Adult",
        "image_url": "https://images.gr-assets.com/books/1522157426l/19063.jpg",
        "Quote1": "“You don’t forget the face of the person who was your last hope.”",
        "Quote2": "“Remember, we're madly in love, so it's all right to kiss me anytime you feel like it.”",
        "Quote3": "“May the odds be ever in your favor!”"
      },
      {
        "id": 7,
        "title": "The Chronicles of Narnia",
        "authors": "C.S. Lewis",
        "description": "Journeys to the end of the world, fantastic creatures, and epic battles between good and evil—what more could any reader ask for in one book? The book that has it all is The Lion, the Witch and the Wardrobe, written in 1949 by Clive Staples Lewis. But Lewis did not stop there. Six more books followed, and together they became known as The Chronicles of Narnia.For the past fifty years, The Chronicles of Narnia have transcended the fantasy genre to become part of the canon of classic literature. Each of the seven books is a masterpiece, drawing the reader into a land where magic meets reality, and the result is a fictional world whose scope has fascinated generations.This edition presents all seven books—unabridged—in one impressive volume. The books are presented here in chronlogical order, each chapter graced with an illustration by the original artist, Pauline Baynes. Deceptively simple and direct, The Chronicles of Narnia continue to captivate fans with adventures, characters, and truths that speak to readers of all ages, even fifty years after they were first published.",
        "edition": "Reissue Edition",
        "format": "Paperback",
        "num_pages": 767,
        "rating": 4.25,
        "rating_count": 437829,
        "review_count": 9439,
        "genres": "Fantasy, Classics, Fiction, Young Adult, Childrens",
        "genre_list": "Fantasy,Classics,Fiction,Young Adult,Childrens",
        "image_url": "https://images.gr-assets.com/books/1449868701l/11127.jpg",
        "Quote1": "“Wit beyond measure is man’s greatest treasure.”",
        "Quote2": "“Indifference and neglect often do much more damage than outright dislike.”",
        "Quote3": "“Things we lose have a way of coming back to us in the end, if not always in the way we expect.”"
      },
      {
        "id": 8,
        "title": "Animal Farm",
        "authors": "George Orwell",
        "description": "A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned –a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible.\nWhen Animal Farm was first published, Stalinist Russia was seen as its target. Today it is devastatingly clear that wherever and whenever freedom is attacked, under whatever banner, the cutting clarity and savage comedy of George Orwell’s masterpiece have a meaning and message still ferociously fresh.",
        "edition": "",
        "format": "Paperback",
        "num_pages": 122,
        "rating": 3.9,
        "rating_count": 2235084,
        "review_count": 42156,
        "genres": "Classics, Fiction, Science Fiction, Dystopia, Fantasy, Literature, Academic, School, Politics, Science Fiction, Novels, Academic, Read For School",
        "genre_list": "Classics,Fiction,Science Fiction,Dystopia,Fantasy,Literature,Academic,School,Politics,Novels,Read For School",
        "image_url": "https://images.gr-assets.com/books/1424037542l/7613.jpg",
        "Quote1": "“Until I feared I would lose it, I never loved to read. One does not love breathing.”",
        "Quote2": "“People generally see what they look for, and hear what they listen for.”",
        "Quote3": "“The one thing that doesn't abide by majority rule is a person's conscience.”"
      },
      {
        "id": 9,
        "title": "Gone with the Wind",
        "authors": "Margaret Mitchell",
        "description": "Gone with the Wind is a novel written by Margaret Mitchell, first published in 1936. The story is set in Clayton County, Georgia, and Atlanta during the American Civil War and Reconstruction era. It depicts the struggles of young Scarlett O'Hara, the daughter of a well-to-do plantation owner, who must use every means at her disposal to claw her way out of the poverty she finds herself in after Sherman's March to the Sea. A historical novel, the story is a Bildungsroman or coming-of-age story, with the title taken from a poem written by Ernest Dowson.",
        "edition": "",
        "format": "Paperback",
        "num_pages": 1037,
        "rating": 4.29,
        "rating_count": 969181,
        "review_count": 17452,
        "genres": "Classics, Historical, Historical Fiction, Fiction, Romance, Historical",
        "genre_list": "Classics,Historical,Historical Fiction,Fiction,Romance",
        "image_url": "https://images.gr-assets.com/books/1328025229l/18405.jpg",
        "Quote1": "“A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.”",
        "Quote2": "“It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.”",
        "Quote3": "“I must learn to be content with being happier than I deserve.”"
      },
      {
        "id": 10,
        "title": "J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings",
        "authors": "J.R.R. Tolkien",
        "description": "This four-volume, boxed set contains J.R.R. Tolkien's epic masterworks The Hobbit and the three volumes of The Lord of the Rings (The Fellowship of the Ring, The Two Towers, and The Return of the King).",
        "edition": "Hobbit Movie Tie-in Boxed set",
        "format": "Mass Market Paperback",
        "num_pages": 1728,
        "rating": 4.59,
        "rating_count": 99793,
        "review_count": 1652,
        "genres": "Fantasy, Fiction, Classics",
        "genre_list": "Fantasy,Fiction,Classics",
        "image_url": "https://images.gr-assets.com/books/1346072396l/30.jpg",
        "Quote1": "“I like the night. Without the dark, we'd never see the stars.”",
        "Quote2": "“I decided as long as I'm going to hell, I might as well do it thoroughly.”",
        "Quote3": "“When life offers you a dream so far beyond any of your expectations, it’s not reasonable to grieve when it comes to an end.”"
      },
      {
        "id": 11,
        "title": "The Fault in Our Stars",
        "authors": "John Green",
        "description": "Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazel's story is about to be completely rewritten.Insightful, bold, irreverent, and raw, The Fault in Our Stars is award-winning author John Green's most ambitious and heartbreaking work yet, brilliantly exploring the funny, thrilling, and tragic business of being alive and in love.",
        "edition": "",
        "format": "Hardcover",
        "num_pages": 313,
        "rating": 4.24,
        "rating_count": 2881648,
        "review_count": 147270,
        "genres": "Young Adult, Fiction, Romance, Contemporary",
        "genre_list": "Young Adult,Fiction,Romance,Contemporary",
        "image_url": "https://images.gr-assets.com/books/1360206420l/11870085.jpg",
        "Quote1": "“You don’t forget the face of the person who was your last hope.”",
        "Quote2": "“Remember, we're madly in love, so it's all right to kiss me anytime you feel like it.”",
        "Quote3": "“May the odds be ever in your favor!”"
      },
      {
        "id": 12,
        "title": "The Hitchhiker's Guide to the Galaxy",
        "authors": "Douglas Adams",
        "description": "Seconds before the Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker's Guide to the Galaxy who, for the last fifteen years, has been posing as an out-of-work actor.Together this dynamic pair begin a journey through space aided by quotes from The Hitchhiker's Guide (\"A towel is about the most massively useful thing an interstellar hitchhiker can have\") and a galaxy-full of fellow travelers: Zaphod Beeblebrox—the two-headed, three-armed ex-hippie and totally out-to-lunch president of the galaxy; Trillian, Zaphod's girlfriend (formally Tricia McMillan), whom Arthur tried to pick up at a cocktail party once upon a time zone; Marvin, a paranoid, brilliant, and chronically depressed robot; Veet Voojagig, a former graduate student who is obsessed with the disappearance of all the ballpoint pens he bought over the years.",
        "edition": "",
        "format": "Paperback",
        "num_pages": 193,
        "rating": 4.21,
        "rating_count": 1155911,
        "review_count": 23919,
        "genres": "Science Fiction, Fiction, Humor, Fantasy, Classics",
        "genre_list": "Science Fiction,Fiction,Humor,Fantasy,Classics",
        "image_url": "https://images.gr-assets.com/books/1388282444l/386162.jpg",
        "Quote1": "“Wit beyond measure is man’s greatest treasure.”",
        "Quote2": "“Indifference and neglect often do much more damage than outright dislike.”",
        "Quote3": "“Things we lose have a way of coming back to us in the end, if not always in the way we expect.”"
      },
      {
        "id": 13,
        "title": "The Giving Tree",
        "authors": "Shel Silverstein",
        "description": "\"Once there was a tree...and she loved a little boy.\"So begins a story of unforgettable perception, beautifully written and illustrated by the gifted and versatile Shel Silverstein.Every day the boy would come to the tree to eat her apples, swing from her branches, or slide down her trunk...and the tree was happy. But as the boy grew older he began to want more from the tree, and the tree gave and gave and gave.This is a tender story, touched with sadness, aglow with consolation. Shel Silverstein has created a moving parable for readers of all ages that offers an affecting interpretation of the gift of giving and a serene acceptance of another's capacity to love in return.",
        "edition": "",
        "format": "Hardcover",
        "num_pages": 64,
        "rating": 4.37,
        "rating_count": 789681,
        "review_count": 15694,
        "genres": "Childrens, Childrens, Picture Books, Classics, Fiction",
        "genre_list": "Childrens,Picture Books,Classics,Fiction",
        "image_url": "https://images.gr-assets.com/books/1174210942l/370493.jpg",
        "Quote1": "“Until I feared I would lose it, I never loved to read. One does not love breathing.”",
        "Quote2": "“People generally see what they look for, and hear what they listen for.”",
        "Quote3": "“The one thing that doesn't abide by majority rule is a person's conscience.”"
      },
      {
        "id": 14,
        "title": "Wuthering Heights",
        "authors": "Emily Brontë",
        "description": "You can find the redesigned cover of this edition HERE.This best-selling Norton Critical Edition is based on the 1847 first edition of the novel. For the Fourth Edition, the editor has collated the 1847 text with several modern editions and has corrected a number of variants, including accidentals. The text is accompanied by entirely new explanitory annotations.New to the fourth Edition are twelve of Emily Bronte's letters regarding the publication of the 1847 edition of Wuthering Heights as well as the evolution of the 1850 edition, prose and poetry selections by the author, four reviews of the novel, and poetry selections by the author, four reviews of the novel, and Edward Chitham's insightful and unformative chronology of the creative process behind the beloved work.Five major critical interpretations of Wuthering Heights are included, three of them new to the Fourth Edition. A Stuart Daley considers teh mimportance of chronology in the novel. J. Hillis Miller examines Wuthering Heights's problems of genre and critical reputation. Sandra M. Gilbert asseses the role of Victorian Christianity plays in the novel, while Martha Nussbaum traces the novel's romanticism. Finally, Lin Haire-Sargeant scrutinizes the role of Heathcliff in film adaptations of Wuthering Heights. A Chronology and updated Selected Bibliography are also included.(back cover)",
        "edition": "Fourth Edition",
        "format": "Paperback",
        "num_pages": 464,
        "rating": 3.84,
        "rating_count": 1121100,
        "review_count": 29400,
        "genres": "Classics, Fiction, Romance, Literature",
        "genre_list": "Classics,Fiction,Romance,Literature",
        "image_url": "https://images.gr-assets.com/books/1388212715l/6185.jpg",
        "Quote1": "“A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.”",
        "Quote2": "“It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.”",
        "Quote3": "“I must learn to be content with being happier than I deserve.”"
      },
      {
        "id": 15,
        "title": "The Da Vinci Code",
        "authors": "Dan Brown",
        "description": "An ingenious code hidden in the works of Leonardo da Vinci.A desperate race through the cathedrals and castles of Europe.An astonishing truth concealed for centuries . . . unveiled at last.While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter.Even more startling, the late curator was involved in the Priory of Sion—a secret society whose members included Sir Isaac Newton, Victor Hugo, and Da Vinci—and he guarded a breathtaking historical secret. Unless Langdon and Neveu can decipher the labyrinthine puzzle—while avoiding the faceless adversary who shadows their every move—the explosive, ancient truth will be lost forever.",
        "edition": "",
        "format": "Paperback",
        "num_pages": 481,
        "rating": 3.81,
        "rating_count": 1668594,
        "review_count": 43699,
        "genres": "Fiction, Mystery, Thriller",
        "genre_list": "Fiction,Mystery,Thriller",
        "image_url": "https://images.gr-assets.com/books/1303252999l/968.jpg",
        "Quote1": "“I like the night. Without the dark, we'd never see the stars.”",
        "Quote2": "“I decided as long as I'm going to hell, I might as well do it thoroughly.”",
        "Quote3": "“When life offers you a dream so far beyond any of your expectations, it’s not reasonable to grieve when it comes to an end.”"
      },
]

export default mockBooksData;
